[MQTT]
# Adress of MQTT broker
broker = mqtt.example.com
#Port
port = 1883
# MQTT Topic to publish data
topic = segway/S1ABCDEFGHIKLMN

[SCOOTER]
# Bluetooth MAC Adress
adress = AA:BB:CC:DD:EE:FF
# Serial Number / Name
serial = S1ABCDEFGHIKLMN
# Password extracted from the App
password = 
